blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # post list
    url(r'^$', views.post_list, name='post_list'),
    # post detail
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    # post update
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # post share
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    # create new post
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', 
        views.post_list, 
        name='post_list_by_tag'),
]

fitnesslaface/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from blog.sitemaps import PostSitemap
# dictionary of sitemaps
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    # homepage, redirects to post list
    url(r'^$', RedirectView.as_view(
                                    pattern_name='blog:post_list',
                                    permanent=False)),
    # admin panel
    url(r'^admin/', admin.site.urls),
    # blog
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # user account
    url(r'^account/', include('account.urls')),
    # sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

# static media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse 
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
    """Custom manager, can retrieves posts with status 'published'"""
    def get_queryset(self):
        return super(PublishedManager, 
                     self).get_queryset().filter(status='published')


class Tag(models.Model):
    """Tag model"""
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title


class Post(models.Model):
    """Blog post model"""
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    author = models.ForeignKey(User, related_name='blog_posts')
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(upload_to='images/%Y/%m/%d', null=True)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, 
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    objects = models.Manager()
    published = PublishedManager() # custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    def get_update_url(self):
        return reverse('blog:post_edit', kwargs={'year': self.publish.year,
                                                'month': self.publish.month,
                                                'slug': self.slug})


class Comment(models.Model):
    """Comment model"""
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=60)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}.'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment, Post


class SharePostForm(forms.Form):
    """Lets user share the post vie email"""
    name = forms.CharField(max_length=20, 
                           widget=forms.TextInput(attrs={
                                                  'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
                                                     'class': 'form-control'
                                                     }))
    to = forms.EmailField(widget=forms.EmailInput(attrs={
                                                  'class': 'form-control'
                                                  }))
    comments = forms.CharField(required=False, widget=forms.Textarea(
                                            attrs={'class': 'form-control'}))


class CommentForm(forms.ModelForm):
    """Lets users comment on a post"""
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


class PostForm(forms.ModelForm):
    """Lets user create a new post or update an existing one"""
    class Meta:
        model = Post
        fields = ('title', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }




blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, UpdateView
from django.core.mail import send_mail
from django.db.models import Count # performs aggregated counts
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from .models import Post, Comment, Tag
from .forms import SharePostForm, CommentForm, PostForm


def post_list(request, tag_slug=None):
    """Displays the list of all published posts"""
    object_list = Post.published.all() # custom manager
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1) # displays the first page
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) # displays the last page
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                    'page': page,
                                                    'tag': tag})


def post_detail(request, pk):
    """Displays a detailed view of a particular post"""
    post = get_object_or_404(Post, pk=pk)
    # comments
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else: 
        comment_form = CommentForm()
    # list of tags id's of the current post
    post_tags_ids = post.tags.values_list('id', flat=True)
    # get all posts with all those tags excluding the current one
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
                                                                id=post.id)
    # same_tags = number of tags shared with all tags queried
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
                                                    '-same_tags', '-publish')
    return render(request, 'blog/post/detail.html', {'post': post,
                                            'comments': comments,
                                            'comment_form': comment_form,
                                            'similar_posts': similar_posts})


@login_required
def post_create(request):
    """Creates new blog post"""
    if request.method == 'POST':
        form = PostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.status = 'published'
            post.save()
            return redirect(post.get_absolute_url())
    else:
        form = PostForm()
    return render(request, 'blog/post/create.html', {'form': form})


def post_share(request, post_id):
    """Handles post sharing"""
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = SharePostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                                                            cd['name'],
                                                            cd['email'],
                                                            post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                                                            post.title,
                                                            post_url,
                                                            cd['name'],
                                                            cd['comments'])
            send_mail(subject, message, 'admin@fitnesslaface.com', [cd['to']])
            sent = True
    else: 
        form = SharePostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@login_required
def post_edit(request, pk):
    """Updates an existing blog post"""
    post = get_object_or_404(Post, pk=pk, author=request.user)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.status = 'published'
            post.save()
            return redirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post/edit.html', {'form': form})

blog/templates/blog/post/create.html
{% extends 'blog/base.html' %}
{# context: form #}

{% block title %}Create Post{% endblock %}

{% block content %}

{# create new post #}
<h2>Create new Post</h2>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="Create Post">
</form>

{% endblock %}


blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{# context: post, comments, comment_form, similar_posts #}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

{# blog post #}
<p class="post">
  <h2>{{ post.title }}</h2>
  <span class="label label-info meta">{{ post.publish }} | by {{ post.author }}</span>
  <br>
  <br>
  {{ post.body }}
  <hr>
</p>

{# share post #}
<p>
  <a href="{% url 'blog:post_share' post.id %}" class="btn"><span class="glyphicon glyphicon-share-alt"></span> Share this post</a>
</p>

{# edit post if user is authenticated #}
{% if user.is_authenticated and post.author == user %}
<a href="{% url 'blog:post_edit' pk=post.pk %}" class="btn"><span class="glyphicon glyphicon-edit"></span>    Edit Post</a>
{% endif %}
<hr>

{# similar posts #}
<h4>Similar Posts:</h4>
{% for post in similar_posts %}
<p>
  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
  No similar posts.
{% endfor %}
<hr>

{# total number of comments #}
<h4>{{ comments.count }} comment{{ comments.count|pluralize }}</h4>

{# list of existing comments #}
{% for comment in comments %}
<div class="comment">
  <p class="label label-danger">
   {{ forloop.counter }} {{ comment.name }} | {{ comment.created }}
  </p>
  <p><span class="glyphicon glyphicon-comment"></span>{{ comment.body|linebreaks }}</p>
</div>
{% empty %}
<p>No comments yet.</p>
{% endfor %}
<hr>

{# create a new comment #}
{% if new_comment %}
<h3>Your comment has been added.</h3>
{% else %}
<h4>Post new comment:</h4>
<form action="" method="POST" class="comment-form">
  {% csrf_token %}
  {{ comment_form.as_p }}
  <input type="submit" value="Add comment" class="btn btn-info">
</form>

{% endif %}

{% endblock %}



blog/templates/blog/post/edit.html
{% extends 'blog/base.html' %}
{# context: form  #}

{% block title %}{% endblock %}

{% block content %}

{# edit post #}
<h3>Edit post</h3>
<form action="" method="post" class="edit-form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update" class="btn btn-primary">
</form>



{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{# context: posts, page, tag #}

{% block title %}Blog{% endblock %}

{% block content %}

<h2 class="text-center">Blog</h2>
<hr>

{# posts list #}
{% for post in posts %}

<h3>
  <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
</h3>
<span class="label label-info meta">{{ post.publish }} | by {{ post.author }}</span>
<br>
<span class="tags">
  {% for tag in post.tags.all %}
  <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.title}}</a>
  {% if not forloop.last %}, {% endif %}
  {% endfor %}
</span>
<p>{{ post.body|truncatewords:30|linebreaks }}</p>
<hr>

{% endfor %}

{# pagination #}
<div class="pagination">
  <span class="step-links">
  {% with page=posts %}
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary">Previous</a>
    {% endif %}
    <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" class="btn btn-primary">Next</a>
    {% endif %}
  {% endwith %}
  </span>
</div>

{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}

  {% if sent %}
     <h1>E-mail successfully sent</h1>
     <p>"{{ post.title }}" was successfully sent.</p>
  {% else %}
      <h2 class="text-center">Share "{{ post.title}}" by e-mail</h2>
      <form action="" method="post" id="share-form"> 
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Send" class="btn btn-primary">
      </form>
  {% endif %}

{% endblock  %}